spring:
  profiles:
    active: local

  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

  jackson:
    time-zone: Asia/Seoul

  mvc:
    servlet:
      path: /api

  ai:
    google:
      genai:
        api-key: "AIzaSyCNdRwT_USD2UXyDiYsv92jSYLRp387VP0"
        chat:
          options:
            model: gemini-2.0-flash
            temperature: 1.0
            google-search-retrieval: true
