services:
  app:
    build: .
    image: ticketing-api:latest
    container_name: ticketing-api
    ports:
      - "8000:8080"
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/swyp
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      GOOGLE_GENAI_API_KEY: ${GOOGLE_GENAI_API_KEY}
      EXHIBITION_API_BASE_URL: ${EXHIBITION_API_BASE_URL}
      EXHIBITION_API_SERVICE_KEY: ${EXHIBITION_API_SERVICE_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped


  mysql:
    image: mysql:9.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: swyp
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus-prod.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    command:
      - "--mysqld.username=${DB_USER}:${DB_PASSWORD}"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql-data:
    name: swyp-mysql
  prometheus-data:
    name: swyp-prometheus
  grafana-data:
    name: swyp-grafana

networks:
  default:
    name: swyp-network
