global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ticketing-api"
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "mysqld-exporter"
    static_configs:
      - targets: ["mysql-exporter:9104"]
