spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/swyp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: dev
    password: dev1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/mock
